package server

/*
Copyright 2024 The external-dns-infoblox-webhook Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"context"
	"errors"
	"fmt"
	"net"
	"net/http"
	"os/signal"
	"syscall"

	"github.com/AbsaOSS/external-dns-infoblox-webhook/cmd/webhook/init/configuration"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	log "github.com/sirupsen/logrus"
	"sigs.k8s.io/external-dns/provider"
	"sigs.k8s.io/external-dns/provider/webhook/api"
)

type WebhookServer struct {
	Ready   bool
	Channel chan struct{}
}

func NewServer() *WebhookServer {
	return &WebhookServer{
		Ready:   false,
		Channel: make(chan struct{}, 1),
	}
}

// Start server initialization function
// The server will respond to the following endpoints:
// - / (GET): initialization, negotiates headers and returns the domain filter
// - /records (GET): returns the current records
// - /records (POST): applies the changes
// - /adjustendpoints (POST): executes the AdjustEndpoints method
//
// It runs until SIGINT/SIGTERM, then shuts down the server (see serve). When
// ServerShutdownTimeout is positive it first drains in-flight requests so a
// normal pod termination does not abort an in-flight apply; with the default of
// 0 (or any non-positive value) it closes immediately, aborting in-flight
// requests much as the pre-graceful-shutdown code did. The process now
// always installs a signal handler and catches the first signal rather than
// exiting on its default disposition. It mirrors the endpoints registered by
// api.StartHTTPApi. Start returns an error if it cannot bind the configured
// address; otherwise it blocks until the server has shut down.
func (wh *WebhookServer) Start(config configuration.Config, p provider.Provider) error {
	addr := fmt.Sprintf("%s:%d", config.ServerHost, config.ServerPort)
	l, err := net.Listen("tcp", addr)
	if err != nil {
		return fmt.Errorf("webhook server failed to listen on %s: %w", addr, err)
	}

	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	wh.serve(ctx, stop, l, config, p)
	return nil
}

// serve runs the webhook API on l, signals readiness on wh.Channel once it is
// listening, and, when ctx is cancelled (SIGINT/SIGTERM), drains in-flight
// requests for up to config.ServerShutdownTimeout before returning, or closes
// immediately when that timeout is 0. As soon as shutdown begins it calls stop
// to deregister the signal handler, so a repeated SIGINT/SIGTERM gets its
// default disposition (immediate termination) rather than being swallowed.
//
// Draining matters because external-dns applies a data record and its registry
// ownership TXT as separate, sequential WAPI calls within a single /records
// request (see the infoblox provider's submitChanges). Letting the in-flight
// request finish avoids cutting that sequence mid-pair on a normal pod
// termination, which would strand a half-created or half-deleted record in the
// grid. serve is split out from Start so tests can drive it with a context
// rather than real OS signals.
func (wh *WebhookServer) serve(ctx context.Context, stop func(), l net.Listener, config configuration.Config, p provider.Provider) {
	// These routes mirror api.StartHTTPApi (sigs.k8s.io/external-dns v0.14.2).
	// We register them by hand rather than calling StartHTTPApi because that
	// helper owns the net listener and the s.Serve call, leaving no seam for a
	// graceful shutdown. Re-check this list against upstream whenever the
	// external-dns dependency is bumped: a new or renamed webhook route will not
	// surface as a compile error here, it will just 404 at runtime.
	whAPI := &api.WebhookServer{Provider: p}
	m := http.NewServeMux()
	m.HandleFunc("/", whAPI.NegotiateHandler)
	m.HandleFunc("/records", whAPI.RecordsHandler)
	m.HandleFunc("/adjustendpoints", whAPI.AdjustEndpointsHandler)

	// SERVER_READ_TIMEOUT/SERVER_WRITE_TIMEOUT are intentionally left unwired
	// (as on main): a WriteTimeout shorter than a slow /records apply would drop
	// the connection before the apply can respond, so external-dns would retry an
	// apply that already ran, the mid-apply cutoff the graceful drain exists to
	// prevent. Wire them only as a deliberate, documented change if a use case
	// arises.
	s := &http.Server{
		Handler: m,
	}

	// signal readiness (consumed by the health handler) once we are listening.
	// wh.Channel is always allocated by NewServer, the only constructor.
	wh.Channel <- struct{}{}

	errCh := make(chan error, 1)
	go func() { errCh <- s.Serve(l) }()

	select {
	case err := <-errCh:
		if err != nil && !errors.Is(err, http.ErrServerClosed) {
			log.Fatalf("webhook server stopped: %s", err)
		}
		return
	case <-ctx.Done():
		// The drain is starting; deregister the signal handler so a second
		// SIGINT/SIGTERM terminates the process immediately (its default
		// disposition) instead of being swallowed, letting an operator escalate
		// a stuck drain without resorting to SIGKILL.
		stop()
	}

	if config.ServerShutdownTimeout <= 0 {
		// A non-positive ServerShutdownTimeout disables the drain (see
		// configuration.Config): close the server immediately, aborting any
		// in-flight requests, rather than draining. Guarding with <= 0 (not == 0)
		// keeps a negative misconfiguration from falling through to the
		// already-expired context.WithTimeout below.
		log.Info("closing webhook server immediately (drain disabled)")
		if err := s.Close(); err != nil {
			log.Warnf("webhook server did not close cleanly: %v", err)
		}
	} else {
		shutdownCtx, cancel := context.WithTimeout(context.Background(), config.ServerShutdownTimeout)
		defer cancel()
		log.Infof("draining webhook server before shutdown (timeout %s)", config.ServerShutdownTimeout)
		if err := s.Shutdown(shutdownCtx); err != nil {
			log.Warnf("webhook server did not drain cleanly: %v", err)
		}
	}

	// Surface a genuine Serve error that raced with the shutdown signal: if
	// ctx.Done() won the select above, errCh may still hold a real listen/accept
	// error rather than the http.ErrServerClosed that Close/Shutdown produces.
	// Without this read that error would be lost and the process would exit 0.
	if err := <-errCh; err != nil && !errors.Is(err, http.ErrServerClosed) {
		log.Errorf("webhook server stopped with error during shutdown: %s", err)
	}
}

func (wh *WebhookServer) StartHealth(config configuration.Config) {
	go func() {
		listenAddr := fmt.Sprintf("0.0.0.0:%d", config.HealthCheckPort)
		m := http.NewServeMux()
		m.Handle("/metrics", promhttp.Handler())
		m.HandleFunc("/healthz", func(w http.ResponseWriter, r *http.Request) {
			select {
			case <-wh.Channel:
				wh.Ready = true
			default:
			}
			if wh.Ready {
				w.WriteHeader(http.StatusOK)
				return
			}
			w.WriteHeader(http.StatusInternalServerError)
		})
		s := &http.Server{
			Addr:    listenAddr,
			Handler: m,
		}

		l, err := net.Listen("tcp", listenAddr)
		if err != nil {
			log.Fatal(err)
		}
		err = s.Serve(l)
		if err != nil {
			log.Fatalf("health listener stopped : %s", err)
		}
	}()
}
