package server

/*
Copyright 2024 The external-dns-infoblox-webhook Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"context"
	"fmt"
	"io"
	"net"
	"net/http"
	"reflect"
	"strings"
	"testing"
	"time"

	"github.com/AbsaOSS/external-dns-infoblox-webhook/cmd/webhook/init/configuration"
	log "github.com/sirupsen/logrus"
	"sigs.k8s.io/external-dns/endpoint"
	"sigs.k8s.io/external-dns/plan"
)

type testCase struct {
	name                      string
	returnRecords             []*endpoint.Endpoint
	returnAdjustedEndpoints   []*endpoint.Endpoint
	returnDomainFilter        endpoint.DomainFilter
	hasError                  error
	method                    string
	path                      string
	headers                   map[string]string
	body                      string
	expectedStatusCode        int
	expectedResponseHeaders   map[string]string
	expectedBody              string
	expectedChanges           *plan.Changes
	expectedEndpointsToAdjust []*endpoint.Endpoint
	log.Ext1FieldLogger
}

var mockProvider *MockProvider

func TestMain(m *testing.M) {
	mockProvider = &MockProvider{}

	go func() {
		srv := NewServer()
		cfg := configuration.Init()
		srv.StartHealth(cfg)
		l, err := net.Listen("tcp", fmt.Sprintf("%s:%d", cfg.ServerHost, cfg.ServerPort))
		if err != nil {
			log.Fatal(err)
		}
		// Drive serve directly rather than Start so the test binary does not
		// install a process-wide SIGINT/SIGTERM handler. Start's handler would
		// never be removed here (this goroutine blocks forever), so it would
		// swallow the first Ctrl-C sent to abort a test run.
		srv.serve(context.Background(), func() {}, l, cfg, mockProvider)
	}()

	time.Sleep(300 * time.Millisecond)

	m.Run()
}

func TestRecords(t *testing.T) {
	testCases := []testCase{
		{
			name: "valid case",
			returnRecords: []*endpoint.Endpoint{
				{
					DNSName:    "test.example.com",
					Targets:    []string{""},
					RecordType: "A",
					RecordTTL:  3600,
					Labels: map[string]string{
						"label1": "value1",
					},
				},
			},
			method:             http.MethodGet,
			headers:            map[string]string{"Accept": "application/external.dns.webhook+json;version=1"},
			path:               "/records",
			body:               "",
			expectedStatusCode: http.StatusOK,
			expectedResponseHeaders: map[string]string{
				"Content-Type": "application/external.dns.webhook+json;version=1",
			},
			expectedBody: "[{\"dnsName\":\"test.example.com\",\"targets\":[\"\"],\"recordType\":\"A\",\"recordTTL\":3600,\"labels\":{\"label1\":\"value1\"}}]",
		},
		{
			name:               "backend error",
			hasError:           fmt.Errorf("backend error"),
			method:             http.MethodGet,
			headers:            map[string]string{"Accept": "application/external.dns.webhook+json;version=1"},
			path:               "/records",
			body:               "",
			expectedStatusCode: http.StatusInternalServerError,
		},
	}

	executeTestCases(t, testCases)
}

func TestApplyChanges(t *testing.T) {
	testCases := []testCase{
		{
			name:   "valid case",
			method: http.MethodPost,
			headers: map[string]string{
				"Content-Type": "application/external.dns.webhook+json;version=1",
			},
			path: "/records",
			body: `
{
    "Create": [
        {
            "dnsName": "test.example.com",
            "targets": ["11.11.11.11"],
            "recordType": "A",
            "recordTTL": 3600,
            "labels": {
                "label1": "value1",
                "label2": "value2"
            }
        }
    ]
}`,
			expectedStatusCode:      http.StatusNoContent,
			expectedResponseHeaders: map[string]string{},
			expectedBody:            "",
			expectedChanges: &plan.Changes{
				Create: []*endpoint.Endpoint{
					{
						DNSName:    "test.example.com",
						Targets:    []string{"11.11.11.11"},
						RecordType: "A",
						RecordTTL:  3600,
						Labels: map[string]string{
							"label1": "value1",
							"label2": "value2",
						},
					},
				},
			},
		},
		{
			name:   "valid case with updates",
			method: http.MethodPost,
			headers: map[string]string{
				"Content-Type": "application/external.dns.webhook+json;version=1",
			},
			path: "/records",
			body: `
{
    "UpdateOld": [
        {
            "dnsName": "test.example.com",
            "targets": ["11.11.11.11"],
            "recordType": "A",
            "recordTTL": 3600,
            "labels": {
                "label1": "value1",
                "label2": "value2"
            }
        }
    ],
	 "UpdateNew": [
        {
            "dnsName": "test.example.com",
            "targets": ["22.22.22.22"],
            "recordType": "A",
            "recordTTL": 3600,
            "labels": {
                "label1": "value1",
                "label2": "value2"
            }
        }
    ]
}`,
			expectedStatusCode:      http.StatusNoContent,
			expectedResponseHeaders: map[string]string{},
			expectedBody:            "",
			expectedChanges: &plan.Changes{
				UpdateOld: []*endpoint.Endpoint{
					{
						DNSName:    "test.example.com",
						Targets:    []string{"11.11.11.11"},
						RecordType: "A",
						RecordTTL:  3600,
						Labels: map[string]string{
							"label1": "value1",
							"label2": "value2",
						},
					},
				},
				UpdateNew: []*endpoint.Endpoint{
					{
						DNSName:    "test.example.com",
						Targets:    []string{"22.22.22.22"},
						RecordType: "A",
						RecordTTL:  3600,
						Labels: map[string]string{
							"label1": "value1",
							"label2": "value2",
						},
					},
				},
			},
		},
		{
			name:     "backend error",
			hasError: fmt.Errorf("backend error"),
			method:   http.MethodPost,
			headers: map[string]string{
				"Content-Type": "application/external.dns.webhook+json;version=1",
				"Accept":       "application/external.dns.webhook+json;version=1",
			},
			path: "/records",
			body: `
{
    "Create": [
        {
            "dnsName": "test.example.com",
            "targets": ["11.11.11.11"],
            "recordType": "A",
            "recordTTL": 3600,
            "labels": {
                "label1": "value1",
                "label2": "value2"
            }
        }
    ]
}`,
			expectedStatusCode: http.StatusInternalServerError,
		},
	}

	executeTestCases(t, testCases)
}

func TestAdjustEndpoints(t *testing.T) {
	testCases := []testCase{
		{
			name: "happy case",
			returnAdjustedEndpoints: []*endpoint.Endpoint{
				{
					DNSName:    "adjusted.example.com",
					Targets:    []string{""},
					RecordType: "A",
					RecordTTL:  3600,
					Labels: map[string]string{
						"label1": "value1",
					},
				},
			},
			method: http.MethodPost,
			headers: map[string]string{
				"Content-Type": "application/external.dns.webhook+json;version=1",
				"Accept":       "application/external.dns.webhook+json;version=1",
			},
			path: "/adjustendpoints",
			body: `
[
	{
		"dnsName": "toadjust.example.com",
		"targets": [],
		"recordType": "A",
		"recordTTL": 3600,
		"labels": {
			"label1": "value1",
			"label2": "value2"
		}
	}
]`,
			expectedStatusCode: http.StatusOK,
			expectedResponseHeaders: map[string]string{
				"Content-Type": "application/external.dns.webhook+json;version=1",
			},
			expectedBody: "[{\"dnsName\":\"adjusted.example.com\",\"targets\":[\"\"],\"recordType\":\"A\",\"recordTTL\":3600,\"labels\":{\"label1\":\"value1\"}}]",
			expectedEndpointsToAdjust: []*endpoint.Endpoint{
				{
					DNSName:    "toadjust.example.com",
					Targets:    []string{},
					RecordType: "A",
					RecordTTL:  3600,
					Labels: map[string]string{
						"label1": "value1",
						"label2": "value2",
					},
				},
			},
		},
		{
			name:   "invalid json",
			method: http.MethodPost,
			headers: map[string]string{
				"Content-Type": "application/external.dns.webhook+json;version=1",
				"Accept":       "application/external.dns.webhook+json;version=1",
			},
			path:                    "/adjustendpoints",
			body:                    "invalid",
			expectedStatusCode:      http.StatusBadRequest,
			expectedResponseHeaders: map[string]string{},
			expectedBody:            "",
		},
	}

	executeTestCases(t, testCases)
}

func TestNegotiate(t *testing.T) {
	testCases := []testCase{
		{
			name:               "happy case",
			returnDomainFilter: endpoint.NewDomainFilter([]string{"a.de"}),
			method:             http.MethodGet,
			headers:            map[string]string{"Accept": "application/external.dns.webhook+json;version=1"},
			path:               "/",
			body:               "",
			expectedStatusCode: http.StatusOK,
			expectedResponseHeaders: map[string]string{
				"Content-Type": "application/external.dns.webhook+json;version=1",
			},
			expectedBody: `{"include":["a.de"]}`,
		},
		{
			name:               "no accept header",
			method:             http.MethodGet,
			headers:            map[string]string{},
			path:               "/",
			body:               "",
			expectedStatusCode: http.StatusOK,
			expectedResponseHeaders: map[string]string{
				"Content-Type": "application/external.dns.webhook+json;version=1",
			},
			expectedBody: "{}",
		},
	}

	executeTestCases(t, testCases)
}

func executeTestCases(t *testing.T, testCases []testCase) {
	log.SetLevel(log.DebugLevel)

	for i, tc := range testCases {
		t.Run(fmt.Sprintf("%d. %s", i+1, tc.name), func(t *testing.T) {
			mockProvider.testCase = tc
			mockProvider.t = t

			var bodyReader io.Reader = strings.NewReader(tc.body)

			request, err := http.NewRequest(tc.method, "http://localhost:8888"+tc.path, bodyReader)
			if err != nil {
				t.Error(err)
			}

			for k, v := range tc.headers {
				request.Header.Set(k, v)
			}

			response, err := http.DefaultClient.Do(request)
			if err != nil {
				t.Error(err)
			}

			if response.StatusCode != tc.expectedStatusCode {
				t.Errorf("expected status code %d, got %d", tc.expectedStatusCode, response.StatusCode)
			}

			for k, v := range tc.expectedResponseHeaders {
				if response.Header.Get(k) != v {
					t.Errorf("expected header '%s' with value '%s', got '%s'", k, v, response.Header.Get(k))
				}
			}

			if tc.expectedBody != "" {
				body, err := io.ReadAll(response.Body)
				if err != nil {
					t.Error(err)
				}
				_ = response.Body.Close()
				actualTrimmedBody := strings.TrimSpace(string(body))
				if actualTrimmedBody != tc.expectedBody {
					t.Errorf("expected body '%s', got '%s'", tc.expectedBody, actualTrimmedBody)
				}
			}
		})
	}
}

type MockProvider struct {
	t        *testing.T
	testCase testCase
}

func (d *MockProvider) Records(_ context.Context) ([]*endpoint.Endpoint, error) {
	return d.testCase.returnRecords, d.testCase.hasError
}

func (d *MockProvider) ApplyChanges(_ context.Context, changes *plan.Changes) error {
	if d.testCase.hasError != nil {
		return d.testCase.hasError
	}
	if !reflect.DeepEqual(changes, d.testCase.expectedChanges) {
		d.t.Errorf("expected changes '%v', got '%v'", d.testCase.expectedChanges, changes)
	}
	return nil
}

func (d *MockProvider) AdjustEndpoints(endpoints []*endpoint.Endpoint) ([]*endpoint.Endpoint, error) {
	if !reflect.DeepEqual(endpoints, d.testCase.expectedEndpointsToAdjust) {
		d.t.Errorf("expected endpoints to adjust '%v', got '%v'", d.testCase.expectedEndpointsToAdjust, endpoints)
	}
	return d.testCase.returnAdjustedEndpoints, nil
}

func (d *MockProvider) GetDomainFilter() endpoint.DomainFilter {
	return d.testCase.returnDomainFilter
}

// slowApplyProvider blocks in ApplyChanges until release is closed, so a test
// can hold a request in flight and observe how a graceful shutdown treats it.
type slowApplyProvider struct {
	*MockProvider
	applyStarted chan struct{} // closed when ApplyChanges is entered
	release      chan struct{} // ApplyChanges returns once this is closed
}

func (s *slowApplyProvider) ApplyChanges(_ context.Context, _ *plan.Changes) error {
	close(s.applyStarted)
	<-s.release
	return nil
}

// TestServeDrainsInFlightRequestOnShutdown verifies that cancelling serve's
// context (as SIGINT/SIGTERM does) lets an in-flight /records apply run to
// completion instead of being cut off, and that serve then returns. This is
// what stops a normal pod termination from aborting an apply mid-pair.
func TestServeDrainsInFlightRequestOnShutdown(t *testing.T) {
	l, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("listen: %v", err)
	}
	addr := l.Addr().String()

	sp := &slowApplyProvider{
		MockProvider: &MockProvider{},
		applyStarted: make(chan struct{}),
		release:      make(chan struct{}),
	}
	wh := NewServer()
	cfg := configuration.Config{ServerShutdownTimeout: 10 * time.Second}

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	served := make(chan struct{})
	go func() {
		wh.serve(ctx, func() {}, l, cfg, sp)
		close(served)
	}()

	<-wh.Channel // wait until the server is listening

	respCh := make(chan int, 1)
	go func() {
		resp, err := http.Post("http://"+addr+"/records", "application/json", strings.NewReader("{}"))
		if err != nil {
			respCh <- -1
			return
		}
		defer resp.Body.Close()
		respCh <- resp.StatusCode
	}()

	select {
	case <-sp.applyStarted: // the apply is now in flight
	case <-time.After(5 * time.Second):
		t.Fatal("apply did not start; /records never reached ApplyChanges")
	}
	cancel()          // trigger graceful shutdown mid-apply
	close(sp.release) // let the in-flight apply finish while the drain waits

	select {
	case code := <-respCh:
		if code != http.StatusNoContent {
			t.Fatalf("in-flight apply was not drained cleanly: got status %d, want %d", code, http.StatusNoContent)
		}
	case <-time.After(5 * time.Second):
		t.Fatal("in-flight apply did not complete after graceful shutdown was triggered")
	}

	select {
	case <-served:
	case <-time.After(5 * time.Second):
		t.Fatal("serve did not return after draining")
	}
}

// TestServeClosesImmediatelyWhenDrainDisabled verifies that a non-positive
// ServerShutdownTimeout disables the drain: on context cancel serve severs the
// in-flight request and returns immediately instead of draining. A negative
// value must take the same immediate-close (s.Close) path as 0, not fall through
// to an already-expired shutdown context, which would return without
// force-closing, leaving the in-flight request dangling.
func TestServeClosesImmediatelyWhenDrainDisabled(t *testing.T) {
	for _, timeout := range []time.Duration{0, -1 * time.Second} {
		t.Run(timeout.String(), func(t *testing.T) {
			l, err := net.Listen("tcp", "127.0.0.1:0")
			if err != nil {
				t.Fatalf("listen: %v", err)
			}
			addr := l.Addr().String()

			sp := &slowApplyProvider{
				MockProvider: &MockProvider{},
				applyStarted: make(chan struct{}),
				release:      make(chan struct{}),
			}
			// Release the blocked apply only on cleanup so it stays in flight for
			// the whole assertion window.
			defer close(sp.release)
			wh := NewServer()
			cfg := configuration.Config{ServerShutdownTimeout: timeout}

			ctx, cancel := context.WithCancel(context.Background())
			defer cancel()

			served := make(chan struct{})
			go func() {
				wh.serve(ctx, func() {}, l, cfg, sp)
				close(served)
			}()

			<-wh.Channel // wait until the server is listening

			respCh := make(chan int, 1)
			go func() {
				resp, err := http.Post("http://"+addr+"/records", "application/json", strings.NewReader("{}"))
				if err != nil {
					respCh <- -1 // connection severed by the server
					return
				}
				defer resp.Body.Close()
				respCh <- resp.StatusCode
			}()

			select {
			case <-sp.applyStarted: // the apply is now in flight
			case <-time.After(5 * time.Second):
				t.Fatal("apply did not start; /records never reached ApplyChanges")
			}
			cancel() // trigger shutdown with the drain disabled

			// The in-flight request must be severed (not completed with 204):
			// this proves serve force-closed via s.Close rather than falling
			// through to an expired-context Shutdown that leaves the connection open.
			select {
			case code := <-respCh:
				if code == http.StatusNoContent {
					t.Fatal("in-flight apply completed (204); expected it to be aborted")
				}
			case <-time.After(3 * time.Second):
				t.Fatal("in-flight request was not severed; serve did not force-close")
			}

			select {
			case <-served:
			case <-time.After(3 * time.Second):
				t.Fatal("serve did not return after drain-disabled shutdown")
			}
		})
	}
}

// TestServeStopsSignalHandlingOnShutdown verifies that serve deregisters the
// signal handler (invokes the stop callback) as soon as the drain begins, so a
// second SIGINT/SIGTERM during the drain terminates the process immediately
// instead of being swallowed by the still-registered handler.
func TestServeStopsSignalHandlingOnShutdown(t *testing.T) {
	l, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("listen: %v", err)
	}

	wh := NewServer()
	cfg := configuration.Config{ServerShutdownTimeout: time.Second}

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	// stop records that serve deregistered the signal handler. The buffered
	// channel tolerates stop being called more than once, like the real
	// signal.NotifyContext stop function.
	stopped := make(chan struct{}, 1)
	stop := func() {
		select {
		case stopped <- struct{}{}:
		default:
		}
	}

	served := make(chan struct{})
	go func() {
		wh.serve(ctx, stop, l, cfg, &MockProvider{})
		close(served)
	}()

	<-wh.Channel // wait until the server is listening
	cancel()     // trigger graceful shutdown

	select {
	case <-stopped:
		// serve deregistered the signal handler as the drain began.
	case <-time.After(5 * time.Second):
		t.Fatal("serve did not stop signal handling when shutdown was triggered")
	}

	select {
	case <-served:
	case <-time.After(5 * time.Second):
		t.Fatal("serve did not return after shutdown")
	}
}

// TestStartReturnsErrorWhenAddressUnavailable exercises Start's bind/error path
// (and its address formatting) without installing a process-wide signal
// handler: an occupied port makes net.Listen fail, and Start must surface that
// as an error rather than exiting the process.
func TestStartReturnsErrorWhenAddressUnavailable(t *testing.T) {
	busy, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("listen: %v", err)
	}
	defer busy.Close()

	cfg := configuration.Config{
		ServerHost: "127.0.0.1",
		ServerPort: busy.Addr().(*net.TCPAddr).Port,
	}

	if err := NewServer().Start(cfg, &MockProvider{}); err == nil {
		t.Fatal("expected Start to return an error when the address is already in use")
	}
}
