package configuration

/*
Copyright 2024 The external-dns-infoblox-webhook Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"time"

	"github.com/alecthomas/kong"
	log "github.com/sirupsen/logrus"
)

// Config struct for configuration environmental variables
type Config struct {
	ServerHost            string        `name:"server-host" env:"SERVER_HOST" validate:"required" default:"127.0.0.1"`
	ServerPort            int           `name:"server-port" env:"SERVER_PORT" validate:"required" default:"8888"`
	HealthCheckPort       int           `name:"health-check-port" env:"HEALTH_CHECK_PORT" validate:"required" default:"8080"`
	ServerReadTimeout     time.Duration `name:"server-read-timeout" env:"SERVER_READ_TIMEOUT"`
	ServerWriteTimeout    time.Duration `name:"server-write-timeout" env:"SERVER_WRITE_TIMEOUT"`
	ServerShutdownTimeout time.Duration `name:"server-shutdown-timeout" env:"SERVER_SHUTDOWN_TIMEOUT"`
	DomainFilter          []string      `name:"domain-filter" env:"DOMAIN_FILTER" default:""`
	ExcludeDomains        []string      `name:"exclude-domain-filter" env:"EXCLUDE_DOMAIN_FILTER" default:""`
	RegexDomainFilter     string        `name:"regex-domain-filter" env:"REGEXP_DOMAIN_FILTER" default:""`
	RegexDomainExclusion  string        `name:"regex-domain-filter-exclusion" env:"REGEXP_DOMAIN_FILTER_EXCLUSION" default:""`
	RegexNameFilter       string        `name:"regex-name-filter" env:"REGEXP_NAME_FILTER" default:""`
}

// Init sets up configuration by reading set environmental variables
func Init(args []string) Config {
	cfg := &Config{}
	parser, err := kong.New(cfg)
	if err != nil {
		log.Fatalf("Error reading configuration from environment: %v", err)
	}
	_, err = parser.Parse(args)
	if err != nil {
		log.Fatalf("Error parsing configuration from environment: %v", err)
	}
	return *cfg
}
